apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-fastapi-app
spec:
  selector:
    matchLabels:
      app: first-fastapi-app
  template:
    metadata:
      labels:
        app: first-fastapi-app
    spec:
      containers:
      - name: first-fastapi-app
        image: docker.io/kunalkothavade/first-fastapi-app:$(Build.BuildId)
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8516
        envFrom:
        - secretRef:
            name: fastapi-secret
