trigger:
  branches:
    include:
      None  # Runs the pipeline when new code is pushed to main

pool:
  name: 'Default'  # Using a Self-hosted agent

steps:
- task: Docker@2
  displayName: Build Docker Image
  inputs:
    command: build
    dockerfile: 'Dockerfile'
    repository: 'kunalkothavade/first-fastapi-app'
    tags: '$(Build.BuildId)'

- task: Docker@2
  displayName: Push Docker Image to Docker Hub
  inputs:
    command: push
    repository: 'kunalkothavade/first-fastapi-app'
    tags: '$(Build.BuildId)'
    containerRegistry: 'docker-hub-service'  
