trigger: none
  
stages:
- stage : Build
  displayName: Build and Push Docker Image
  jobs: 
  - job: BuildAndPush
    pool:
      name: 'Default'  # Using a Self-hosted agent
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        containerRegistry: 'docker-hub-service'
        repository: 'kunalkothavade/first-fastapi-app'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: 'latest'

- stage: Deploy
  displayName: Deploy to Kubernetes
  jobs:
  - job: DeployToK8s
    pool:
      name: 'Default'  # Use self-hosted agent
    steps:
    - script: |
        kubectl apply -f $(Build.SourcesDirectory)/manifests/deployment.yaml
        kubectl apply -f $(Build.SourcesDirectory)/manifests/service.yaml
      displayName: Deploy to Local Kubernetes
