trigger: none
  
stages:
- stage : Build
  displayName: Build and Push Docker Image
  jobs: 
  - job: BuildAndPush
    pool:
      name: 'Default'  # Using a Self-hosted agent
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        containerRegistry: 'docker-hub-service'
        repository: 'kunalkothavade/first-fastapi-app'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: '$(Build.BuildId)'


