trigger: none
  
stages:
- stage: Deploy
  displayName: Deploy to Kubernetes from Selected Build
  jobs:
  - job: DeployToK8s
    pool:
      name: 'Default'  # Use self-hosted agent
    steps:
    - script: |
        kubectl apply -f $(Build.SourcesDirectory)/manifests/deployment.yaml
        kubectl apply -f $(Build.SourcesDirectory)/manifests/service.yaml
      displayName: Deploy to Local Kubernetes
